version: '3.8'
services:
  harsha:
    build: 
      context: ./harsha
      dockerfile: Dockerfile  # Path to your Rust Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config:/usr/src/myapp/config  # Mount a host directory to store configuration files
    environment:
      - RUST_LOG=info  # Set the Rust log level to 'info'
    #restart: always  # Restart the container automatically if it exits unexpectedly

  kowsi:
    build:
      context: ./kowsi  # Path to your Node.js service directory
      dockerfile: Dockerfile  # Path to your Node.js Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./node_service:/app  # Mount the Node.js service directory
    environment:
      - NODE_ENV=development  # Set the Node.js environment to 'development'
    #restart: always  # Restart the container unless explicitly stopped (note this imp. //unless-stopped)
